[package]
name = "neo-api-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { git = "https://github.com/norlock/mlua", features = ["luajit", "serialize", "module", "async"], branch="fix/lua_module" }
once_cell = "1"
serde = { version = "1", features = ["serde_derive"] }
tokio = { version = "1", features = ["sync"] }
